#!/bin/env Rscript
#SBATCH --mem=40G 
#SBATCH --time=24:00:00 
#SBATCH --partition=BioCompute,Lewis,hpc5
#SBATCH --cpus-per-task=2
#SBATCH --account=warrenlab
#SBATCH --job-name=HeatMap
#SBATCH -o job_files.dir/HeatMap_%j_o.txt

clusters_RDS_filename <- 'objects/clusters_pre_mRNA.rds'

library(Seurat)

clusters <- readRDS(clusters_RDS_filename)


